version: "2"
plugins:
  markdownlint:
    enabled: true
  phan:
    enabled: false
  phpcodesniffer:
    enabled: true
    config:
        standard: "PSR2"
    checks:
      Generic Files LineLength TooLong:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
      - php
  shellcheck:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseVariableName:
        enabled: false
  radon:
    enabled: true
exclude_patterns:
  - "tests/"
  - "lib/"
  - "vendor/"
  - "html/js/"
  - "html/css/"
